// TODO: replace with https://github.com/api3dao/chains/issues/3
module.exports = {
  chainsSupportedByApi3Market: [
    'arbitrum',
    'avalanche',
    'base',
    'bsc',
    'ethereum',
    'fantom',
    'gnosis',
    'kava',
    'linea',
    'mantle',
    'moonbeam',
    'moonriver',
    'optimism',
    'polygon',
    'polygon-zkevm',
    'rsk',
  ],
  chainsSupportedByChainApi: ['ethereum', 'ethereum-goerli-testnet'],
  chainsSupportedByDapis: [
    'arbitrum',
    'arbitrum-goerli-testnet',
    'avalanche',
    'avalanche-testnet',
    'base',
    'base-goerli-testnet',
    'bsc',
    'bsc-testnet',
    'cronos-testnet',
    'ethereum',
    'ethereum-goerli-testnet',
    'ethereum-sepolia-testnet',
    'fantom',
    'fantom-testnet',
    'gnosis',
    'gnosis-testnet',
    'kava',
    'kava-testnet',
    'linea',
    'linea-goerli-testnet',
    'mantle',
    'mantle-goerli-testnet',
    'metis',
    'metis-goerli-testnet',
    'milkomeda-c1',
    'milkomeda-c1-testnet',
    'moonbeam',
    'moonbeam-testnet',
    'moonriver',
    'optimism',
    'optimism-goerli-testnet',
    'polygon',
    'polygon-testnet',
    'polygon-zkevm',
    'polygon-zkevm-goerli-testnet',
    'rsk',
    'rsk-testnet',
    'scroll-goerli-testnet',
    'zksync',
    'zksync-goerli-testnet',
  ],
  chainsSupportedByOevRelay: ['ethereum', 'ethereum-goerli-testnet', 'polygon-testnet'],
};
