// TODO: replace with https://github.com/api3dao/chains/issues/3
module.exports = {
  chainsSupportedByApi3Market: [
    'arbitrum',
    'avalanche',
    'bsc',
    'ethereum',
    'fantom',
    'gnosis',
    'moonbeam',
    'moonriver',
    'optimism',
    'polygon',
    'polygon-zkevm',
  ],
  chainsSupportedByChainApi: ['ethereum', 'ethereum-goerli-testnet'],
  chainsSupportedByDapis: [
    'arbitrum',
    'arbitrum-goerli-testnet',
    'avalanche',
    'avalanche-testnet',
    'bsc',
    'bsc-testnet',
    'ethereum',
    'ethereum-goerli-testnet',
    'ethereum-sepolia-testnet',
    'fantom',
    'fantom-testnet',
    'gnosis',
    'gnosis-testnet',
    'metis',
    'metis-goerli-testnet',
    'milkomeda-c1',
    'milkomeda-c1-testnet',
    'moonbeam',
    'moonbeam-testnet',
    'moonriver',
    'optimism',
    'optimism-goerli-testnet',
    'polygon',
    'polygon-testnet',
    'polygon-zkevm',
    'polygon-zkevm-goerli-testnet',
    'rsk',
    'rsk-testnet',
    'zksync',
    'zksync-goerli-testnet',
  ],
  chainsSupportedByOevRelay: ['ethereum'],
};
